<a href="https://colab.research.google.com/github/pritamdeka/CoLI-Kanglish/blob/main/CoLI_Kanglish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install git+https://github.com/huggingface/transformers
!pip install datasets
!pip install sentencepiece

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/huggingface/transformers to /tmp/pip-req-build-0ozba7el
  Running command git clone -q https://github.com/huggingface/transformers /tmp/pip-req-build-0ozba7el
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 7.6 MB 23.7 MB/s 
     |████████████████████████████████| 182 kB 63.4 MB/s 
  Created wheel for transformers: filename=transformers-4.25.0.dev0-py3-none-any.whl size=5734510 sha256=700f59907d09889be453fdf6be4ff9390703ff33ed68946fdb8c692c66edde05
  Stored in directory: /tmp/pip-ephem-wheel-cache-_xkwwhqa/wheels/35/2e/a7/d819e3310040329f0f47e57c9e3e7a7338aa5e74c49acfe522
Successfully built transformers
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 451 

In [1]:
import pandas as pd
df_train = pd.read_csv(r'/content/Train_Kanglish.csv')
label_dict={'kn': 0, 'en': 1, 'name': 2, 'location': 3, 'en-kn': 4, 'other': 5}
df_train['tag'] = df_train['tag'].map(label_dict)
label_list_train=list(df_train['tag'])
word_list_train=list(df_train['word'])
print(word_list_train)
print(label_list_train)

df_test = pd.read_csv(r'/content/Test_withLabels_Kanglish.csv')
df_test['tag'] = df_test['tag'].map(label_dict)
label_list_test=list(df_test['tag'])
word_list_test = list(df_test['word'])

train_texts = word_list_train
test_texts = word_list_test
train_labels = label_list_train
test_labels = label_list_test
print(train_texts)
print(train_labels)


['anusthu', 'woww', 'staying', 'near', 'hostel', 'confirmed', 'faith', 'linked', 'gotila', 'germany', 'irodhu', 'estondh', 'anside', 'failure', 'motivation', 'sadhne', 'anstide', 'aagidde', 'jayanagarakke', 'kaalitte', 'gotthaythu', 'kalkonde', 'padkonde', 'royal', 'touched', 'kodsi', 'aadri', 'hegilla', 'maathadsodu', 'whom', 'keen', 'observer', 'kamal', 'mohan', 'prakash', 'marlon', 'tom', 'bruce', 'intavrella', 'sensitive', 'saying', 'tune', 'less', 'deserves', 'banner', 'narration', 'above', 'grandfather', 'association', 'benches', 'visit', 'cleaned', 'specs', 'forst', 'doung', 'doors', 'windows', 'body', 'immature', 'none', 'narrated', 'impressed', 'villainous', 'perseverance', 'daaali', 'raani', 'helidange', 'successfully', 'bengalore', 'bandaga', 'padtivi', 'danajaya', 'hega', 'ale', 'eroddhu', 'yesto', 'noderboddhu', 'nodake', 'msg', 'eddhe', 'adarali', 'haguthe', 'yel', 'nenapu', 'whenever', 'possible', 'using', 'idana', 'purthi', 'santhosha', 'anubavisidavaru', 'nijavagalu', 

In [3]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
import logging
import pandas as pd
import numpy as np
from numpy import random
import matplotlib.pyplot as plt
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import roc_auc_score
import gensim
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
import re

nb = Pipeline([('vect', CountVectorizer(ngram_range=(1,4),min_df=1)),
               ('tfidf', TfidfTransformer(sublinear_tf=True)),
               ('clf', (MultinomialNB())),
              ])
nb.fit(train_texts, train_labels)


from sklearn.metrics import classification_report
y_pred = nb.predict(test_texts)

print('accuracy %s' % accuracy_score(y_pred, test_labels))
print(classification_report(test_labels, y_pred))

accuracy 0.4905125408942203
              precision    recall  f1-score   support

           0       0.48      1.00      0.65      2194
           1       0.98      0.03      0.06      1813
           2       0.00      0.00      0.00       354
           3       0.00      0.00      0.00        31
           4       0.00      0.00      0.00        93
           5       0.00      0.00      0.00       100

    accuracy                           0.49      4585
   macro avg       0.24      0.17      0.12      4585
weighted avg       0.62      0.49      0.34      4585



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [4]:
from sklearn.linear_model import SGDClassifier

sgd = Pipeline([('vect', CountVectorizer(ngram_range=(1,2),min_df=1)),
               ('tfidf', TfidfTransformer(sublinear_tf=True)),
                ('clf', (SGDClassifier(loss='hinge', penalty='l2',alpha=1e-4, random_state=42, max_iter=20, tol=1e-3))),
               ])
sgd.fit(train_texts, train_labels)


y_pred = sgd.predict(test_texts)

print('accuracy %s' % accuracy_score(y_pred, test_labels))
print(classification_report(test_labels, y_pred))

accuracy 0.49531079607415485
              precision    recall  f1-score   support

           0       0.49      1.00      0.65      2194
           1       0.98      0.03      0.06      1813
           2       0.86      0.02      0.03       354
           3       1.00      0.10      0.18        31
           4       1.00      0.14      0.25        93
           5       0.50      0.01      0.02       100

    accuracy                           0.50      4585
   macro avg       0.80      0.22      0.20      4585
weighted avg       0.73      0.50      0.35      4585



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_stochastic_gradient.py:700: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  ConvergenceWarning,


In [5]:
from sklearn.linear_model import LogisticRegression

logreg = Pipeline([('vect', CountVectorizer(ngram_range=(1,3),min_df=1)),
               ('tfidf', TfidfTransformer(sublinear_tf=True)),
                ('clf', (LogisticRegression(n_jobs=1, C=1e3))),
               ])
logreg.fit(train_texts, train_labels)

y_pred = logreg.predict(test_texts)

print('accuracy %s' % accuracy_score(y_pred, test_labels))
print(classification_report(test_labels, y_pred))

accuracy 0.49531079607415485
              precision    recall  f1-score   support

           0       0.49      1.00      0.65      2194
           1       0.98      0.03      0.06      1813
           2       0.86      0.02      0.03       354
           3       1.00      0.10      0.18        31
           4       1.00      0.14      0.25        93
           5       0.50      0.01      0.02       100

    accuracy                           0.50      4585
   macro avg       0.80      0.22      0.20      4585
weighted avg       0.73      0.50      0.35      4585



/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [6]:
from sklearn.ensemble import RandomForestClassifier

logreg = Pipeline([('vect', CountVectorizer(ngram_range=(1,3),min_df=1)),
               ('tfidf', TfidfTransformer(sublinear_tf=True)),
                ('clf', RandomForestClassifier(max_depth=10, random_state=65)),
               ])

logreg.fit(train_texts, train_labels)

y_pred = logreg.predict(test_texts)

print('accuracy %s' % accuracy_score(y_pred, test_labels))
print(classification_report(test_labels, y_pred))

accuracy 0.47851690294438387
              precision    recall  f1-score   support

           0       0.48      1.00      0.65      2194
           1       0.00      0.00      0.00      1813
           2       0.00      0.00      0.00       354
           3       0.00      0.00      0.00        31
           4       0.00      0.00      0.00        93
           5       0.00      0.00      0.00       100

    accuracy                           0.48      4585
   macro avg       0.08      0.17      0.11      4585
weighted avg       0.23      0.48      0.31      4585



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow_hub as hub
import logging
logging.basicConfig(level=logging.INFO)
from sklearn.model_selection import train_test_split
import transformers
from transformers import AutoTokenizer,TFBertModel, RobertaTokenizer, TFXLMRobertaModel, TFRobertaModel, DistilBertTokenizer, TFDistilBertModel, TFDebertaModel, TFElectraModel
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Input, Dense
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import ast

##############  uncomment to use that particular model   ########################

tokenizer = AutoTokenizer.from_pretrained('bert-base-uncased')
bert = TFBertModel.from_pretrained('bert-base-uncased')

#tokenizer = AutoTokenizer.from_pretrained('microsoft/deberta-base')
#bert = TFDebertaModel.from_pretrained('microsoft/deberta-base')


#tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
#bert = TFDistilBertModel.from_pretrained("distilbert-base-uncased")

#tokenizer = RobertaTokenizer.from_pretrained('roberta-base')
#bert = TFRobertaModel.from_pretrained('roberta-base')

#tokenizer = AutoTokenizer.from_pretrained('google/electra-base-discriminator')
#bert = TFElectraModel.from_pretrained('google/electra-base-discriminator')


y_train = to_categorical(train_labels, 6)
y_test = to_categorical(test_labels, 6)
max_len = 15
x_train = tokenizer(
    text=train_texts,
    add_special_tokens=True,
    max_length=max_len,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)
x_test = tokenizer(
    text=test_texts,
    add_special_tokens=True,
    max_length=max_len,
    truncation=True,
    padding=True, 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)

input_ids = x_train['input_ids']
attention_mask = x_train['attention_mask']

def bert_model(bert):
  input_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_ids")
  input_mask = Input(shape=(max_len,), dtype=tf.int32, name="attention_mask")
  embeddings = bert(input_ids,attention_mask = input_mask)[0] 
  net = tf.keras.layers.GlobalMaxPool1D()(embeddings)
  net = tf.keras.layers.Dense(128, activation='relu')(net)
  net = tf.keras.layers.Dropout(0.2)(net)
  net = tf.keras.layers.Dense(64, activation='relu')(net)
  net = tf.keras.layers.Dropout(0.2)(net)
  net = tf.keras.layers.Dense(32, activation='relu')(net)
  net = tf.keras.layers.Dropout(0.2)(net)
  y = tf.keras.layers.Dense(6, activation='softmax')(net)
  model = tf.keras.Model(inputs=[input_ids, input_mask], outputs=y)
  optimizer = Adam(
    learning_rate=2e-05,
    epsilon=1e-08,
    decay=0.01,
    clipnorm=1.0)
  # Set loss and metrics
  loss = CategoricalCrossentropy(from_logits = True)
  metric = CategoricalAccuracy('balanced_accuracy')
  model.compile(optimizer = optimizer, loss = loss, metrics = metric)

  return model
model = bert_model(bert)
model.summary()

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 15)]         0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 15)]         0           []                               
                                                                                                  
 tf_bert_model (TFBertModel)    TFBaseModelOutputWi  109482240   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 15,                                            

In [3]:
with tf.device("/device:GPU:0"):
  train_history = model.fit(
    x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']} ,
    y = y_train,
    validation_data = ({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']}, 
                       y_test),
    epochs=20,
    batch_size=128)

Epoch 1/20


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


116/116 [==============================] - 76s 471ms/step - loss: 1.2774 - balanced_accuracy: 0.5525 - val_loss: 0.6770 - val_balanced_accuracy: 0.8207
Epoch 2/20
116/116 [==============================] - 51s 439ms/step - loss: 0.9953 - balanced_accuracy: 0.6709 - val_loss: 0.5961 - val_balanced_accuracy: 0.8410
Epoch 3/20
116/116 [==============================] - 51s 440ms/step - loss: 0.8780 - balanced_accuracy: 0.7146 - val_loss: 0.5713 - val_balanced_accuracy: 0.8471
Epoch 4/20
116/116 [==============================] - 51s 439ms/step - loss: 0.8237 - balanced_accuracy: 0.7330 - val_loss: 0.5506 - val_balanced_accuracy: 0.8478
Epoch 5/20
116/116 [==============================] - 51s 440ms/step - loss: 0.7846 - balanced_accuracy: 0.7448 - val_loss: 0.5346 - val_balanced_accuracy: 0.8495
Epoch 6/20
116/116 [==============================] - 51s 440ms/step - loss: 0.7639 - balanced_accuracy: 0.7530 - val_loss: 0.5472 - val_balanced_accuracy: 0.8414
Epoch 7/20
116/116 [=============

In [4]:
test_pred = model.predict({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']})
y_predicted = np.argmax(test_pred, axis = 1)
y_true = test_labels
arr = np.array(y_true)
print(classification_report(arr, y_predicted))
print(confusion_matrix(arr, y_predicted))

144/144 [==============================] - 10s 49ms/step
              precision    recall  f1-score   support

           0       0.89      0.87      0.88      2194
           1       0.93      0.92      0.93      1813
           2       0.73      0.62      0.67       354
           3       0.00      0.00      0.00        31
           4       0.69      0.69      0.69        93
           5       0.16      0.41      0.23       100

    accuracy                           0.85      4585
   macro avg       0.57      0.58      0.56      4585
weighted avg       0.87      0.85      0.86      4585

[[1904   86   65    0   18  121]
 [  71 1670    6    0   11   55]
 [  99   11  218    0    0   26]
 [   9    2    7    0    0   13]
 [  18    3    1    0   64    7]
 [  38   20    1    0    0   41]]


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
